spring:
  application:
    name: gateway
  config:
    import: optional:file:../infra/.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: core-api
              uri: ${CORE_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/core/**
            - id: core-openapi
              uri: ${CORE_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/aggregate/core/v3/api-docs,/aggregate/core/v3/api-docs/**
              filters:
                - RewritePath=/aggregate/core/(?<segment>.*), /$\{segment}

            - id: resource-api
              uri: ${RESOURCE_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/resource/**
            - id: resource-openapi
              uri: ${RESOURCE_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/aggregate/resource/v3/api-docs,/aggregate/resource/v3/api-docs/**
              filters:
                - RewritePath=/aggregate/resource/(?<segment>.*), /$\{segment}

            - id: booking-api
              uri: ${BOOKING_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/booking/**,/api/admin/booking/**
            - id: booking-websocket
              uri: ${BOOKING_SERVICE_WS_URL:ws://localhost:8083}
              predicates:
                - Path=/ws,/ws/**
                - Header=Upgrade, websocket
            - id: booking-websocket-sockjs
              uri: ${BOOKING_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/ws,/ws/**
            - id: booking-openapi
              uri: ${BOOKING_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/aggregate/booking/v3/api-docs,/aggregate/booking/v3/api-docs/**
              filters:
                - RewritePath=/aggregate/booking/(?<segment>.*), /$\{segment}

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    oauth:
      client-id: ${OAUTH_CLIENT_ID:frontend-client}
      use-pkce-with-authorization-code-grant: true
      scopes: openid profile email
    urls:
      - name: Core
        url: /aggregate/core/v3/api-docs

      - name: Resource
        url: /aggregate/resource/v3/api-docs

      - name: Booking
        url: /aggregate/booking/v3/api-docs


security-filter:
  whitelist:
    - /swagger-ui.html
    - /swagger-ui/**
    - /v3/api-docs
    - /v3/api-docs/**
    - /swagger-resources
    - /swagger-resources/**
    - /webjars/**
    - /aggregate/**

    ## Core Service Open Endpoints
    - /api/core/organization/all/**
    - /api/core/organization/summary/**
    - /api/core/organization/filters/**

    ## Booking Service Open Endpoints
    - /api/booking/resource/availability/**

server:
  port: 8899
