spring:
  application:
    name: gateway
  config:
    import: optional:file:../infra/.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

springdoc:
  swagger-ui:
    urls:
      - name: "Test"
        url: /test/123


security-filter:
  whitelist:
    - /swagger-ui.html
    - /swagger-ui/**
    - /v3/api-docs
    - /v3/api-docs/**
    - /swagger-resources
    - /swagger-resources/**
    - /webjars/**
    - /aggregate/**