name: Gateway CI/CD

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'pom.xml'
      - 'Dockerfile'
      - '.github/workflows/ci.yml'

  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'pom.xml'
      - 'Dockerfile'
      - '.github/workflows/ci.yml'

permissions:
  contents: read
  packages: write

jobs:
  gateway:
    uses: UptimeHub/infra/.github/workflows/java-service-ci.yml@main
    with:
      java-version: 25
      working-directory: "."
      image-name: gateway
      dockerfile: "./Dockerfile"
      docker-context: "."
      publish-image: ${{ github.event_name == 'push' }}
